apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-selinux-disallowed
  name: psp-selinux-v2-disallowed-ephemeral
  labels:
    app: nginx-selinux
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    securityContext:
      seLinuxOptions:
        level: s1:c234,c567
        user: sysadm_u
        role: sysadm_r
        type: svirt_lxc_net_t
