apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-seccomp-disallowed
  name: nginx-seccomp-disallowed
  annotations:
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-seccomp
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
