apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-has-size-limit-example-disallowed
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: bad-pod-volume
      emptyDir: {}
