apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-has-size-limit-example-allowed
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: good-pod-volume
      emptyDir:
        sizeLimit: "2Gi"
