apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: # kpt-merge: default/nginx-pdb-disallowed
  name: nginx-pdb-disallowed
  namespace: default
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      foo: bar
