apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: # kpt-merge: default/inventory-nginx-pdb-allowed-2
  name: inventory-nginx-pdb-allowed-2
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
      example: allowed-deployment-2
