apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: # kpt-merge: default/nginx-pdb-allowed
  name: nginx-pdb-allowed
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      foo: bar
