apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: # kpt-merge: default/inventory-nginx-pdb-allowed-1
  name: inventory-nginx-pdb-allowed-1
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
      example: allowed-deployment-1
