apiVersion: v1
kind: Service
metadata: # kpt-merge: /allowed-external-ip
  name: allowed-external-ip
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 203.0.113.0
