apiVersion: v1
kind: Service
metadata: # kpt-merge: /disallowed-external-ip
  name: disallowed-external-ip
spec:
  selector:
    app: MyApp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
  - 1.1.1.1
