apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-host-filesystem
  name: psp-host-filesystem-disallowed-ephemeral
  labels:
    app: nginx-host-filesystem-disallowed
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # directory location on host
