apiVersion: v1
kind: Pod
metadata: # kpt-merge: /opa-disallowed
  name: container-image-must-not-have-latest-tag-example-no-tag
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
