apiVersion: v1
kind: Pod
metadata: # kpt-merge: /opa-disallowed
  name: opa-disallowed
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
