apiVersion: v1
kind: Pod
metadata: # kpt-merge: /opa-disallowed-2
  name: opa-disallowed-2
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:latest
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
