apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowed-deployment
  annotations:
    network-controls/description: "required network control"
    network-controls/date: "2022-01-01"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
