apiVersion: v1
kind: Service
metadata:
  name: good-aws-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: "TCP"
    targetPort: 8888
