apiVersion: v1
kind: Service
metadata:
  name: bad-aws-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: "TCP"
    targetPort: 8888
