apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-automountserviceaccounttoken-disallowed
  name: nginx-automountserviceaccounttoken-disallowed
  labels:
    app: nginx-automountserviceaccounttoken
spec:
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx
