apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-users-disallowed
  name: psp-pods-allowed-user-ranges-disallowed-ephemeral
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 250
    fsGroup: 250
  ephemeralContainers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 250
        runAsGroup: 250
