apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-host-networking-ports-disallowed
  name: psp-host-networking-ports-disallowed-ephemeral
  labels:
    app: nginx-host-networking-ports
spec:
  hostNetwork: true
  ephemeralContainers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 9001
      hostPort: 9001
