apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-privilege-escalation-disallowed
  name: psp-allow-privilege-escalation-container-disallowed-ephemeral
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  ephemeralContainers:
  - name: nginx2
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
