apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-privilege-escalation-allowed
  name: nginx-privilege-escalation-allowed
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
