apiVersion: v1
kind: Pod
metadata: # kpt-merge: /opa-disallowed
  name: container-image-must-have-digest-example-disallowed
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
  initContainers:
    - args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      image: openpolicyagent/opa:0.9.2
      name: opainit
