apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restrict-clusteradmin-rolebindings-regex-example-disallowed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: 'someotherservice-123456789@gcp-sa-anthosconfigmanagement.iam.gserviceaccount.com'
