apiVersion: v1
kind: Pod
metadata:
  name: example-disallowed-annotation-inject-false
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: sleep
    image: curlimages/curl
