apiVersion: v1
kind: Pod
metadata:
  name: example_disallowed_annotation_inject_false
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: sleep
    image: curlimages/curl
