kind: Suite
apiVersion: test.gatekeeper.sh/v1alpha1
metadata:
  name: k8srequirecosnodeimage
tests:
  - name: k8srequirecosnodeimage
    template: template.yaml
    constraint: samples/nodes-have-consistent-time/constraint.yaml
    cases:
      - name: example-allowed
        object: samples/nodes-have-consistent-time/example_allowed.yaml
        assertions:
          - violations: no
      - name: example-disallowed
        object: samples/nodes-have-consistent-time/example_disallowed.yaml
        assertions:
          - violations: yes
  - name: pci-k8srequirecosnodeimage
    template: template.yaml
    constraint: samples/pci-dss-3.2.1/10.4.1-10.4.3_nodes-have-consistent-time.yaml
    cases:
      - name: example-allowed
        object: samples/nodes-have-consistent-time/example_allowed.yaml
        assertions:
          - violations: no
      - name: example-disallowed
        object: samples/nodes-have-consistent-time/example_disallowed.yaml
        assertions:
          - violations: yes
