apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-host-namespace-disallowed
  name: nginx-host-namespace-disallowed
  labels:
    app: nginx-host-namespace
spec:
  hostPID: true
  hostIPC: true
  containers:
  - name: nginx
    image: nginx
