apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-host-namespace-allowed
  name: nginx-host-namespace-allowed
  labels:
    app: nginx-host-namespace
spec:
  hostPID: false
  hostIPC: false
  containers:
  - name: nginx
    image: nginx
