apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-proc-mount-disallowed
  name: nginx-proc-mount-disallowed
  labels:
    app: nginx-proc-mount
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      procMount: Default
