apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-readonlyrootfilesystem-disallowed
  name: psp-readonlyrootfilesystem-example-disallowed
  labels:
    app: nginx-readonlyrootfilesystem
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      readOnlyRootFilesystem: false
