apiVersion: v1
kind: Pod
metadata:
  name: local-storage-require-safe-to-evict-example-allowed
  namespace: default
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}
