apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sProhibitRoleWildcardAccess
metadata:
  name: prohibit-wildcard-except-exempted-cluster-role
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
      - gke-connect
      - resource-group-system
  parameters:
    exemptions:
      clusterRoles:
        - name: "cluster-role-allowed-example"
      roles:
        - name: "role-allowed-example"
          namespace: "role-ns-allowed-example"
