apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireNamespaceNetworkPolicies
metadata:
  name: require-namespace-network-policies-sample
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
      - config-management-monitoring
      - config-management-system
      - gatekeeper-system
      - gke-connect
      - kube-node-lease
      - kube-public
      - kube-system
      - resource-group-system
