apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sEmptyDirHasSizeLimit
metadata:
  name: empty-dir-has-size-limit
spec:
  enforcementAction: warn
  match:
    excludedNamespaces:
      - config-management-system
      - gatekeeper-system
      - kube-system
  parameters:
    maxSizeLimit: 4Gi
