apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowedRoleBindingSubjects
metadata:
  name: disallowed-rolebinding-subjects
spec:
  enforcementAction: warn
  parameters:
    disallowedSubjects:
    - name: 'system:unauthenticated'
      kind: Group
      apiGroup: rbac.authorization.k8s.io
