apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerRequests
metadata: # kpt-merge: /container-must-have-requests
  name: container-must-have-requests
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
