apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata: # kpt-merge: /repo-is-openpolicyagent
  name: repo-is-openpolicyagent
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "openpolicyagent/"
