apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockNodePort
metadata: # kpt-merge: /block-node-port
  name: block-node-port
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
