apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sUniqueServiceSelector
metadata: # kpt-merge: /unique-service-selector
  name: unique-service-selector
  labels:
    owner: admin.agilebank.demo
spec:
  enforcementAction: warn
