apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerRatios
metadata: # kpt-merge: /container-must-meet-ratio
  name: container-must-meet-ratio
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - config-management-monitoring
      - config-management-system
      - gatekeeper-system
      - gke-connect
      - kube-system
      - resource-group-system
  parameters:
    ratio: "2"
