apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata: # kpt-merge: /container-must-have-limits
  name: container-must-have-limits
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
