apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sReplicaLimits
metadata: # kpt-merge: /replica-limits
  name: replica-limits
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    ranges:
      - min_replicas: 3
        max_replicas: 50
