apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sExternalIPs
metadata: # kpt-merge: /external-ips
  name: external-ips
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    allowedIPs:
      - "203.0.113.0"
