apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAppArmor
metadata: # kpt-merge: /psp-apparmor
  name: psp-apparmor
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles:
      - runtime/default
