apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSeccomp
metadata: # kpt-merge: /psp-seccomp
  name: psp-seccomp
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - config-management-monitoring
      - config-management-system
      - gke-connect
      - kube-system
      - resource-group-system
  parameters:
    allowedProfiles:
      - runtime/default
      - docker/default
