apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPProcMount
metadata: # kpt-merge: /psp-proc-mount
  name: psp-proc-mount
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    procMount: Default
