apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPFSGroup
metadata: # kpt-merge: /psp-fsgroup
  name: psp-fsgroup
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - config-management-monitoring
      - config-management-system
      - gke-connect
      - kube-system
  parameters:
    rule: "MayRunAs" #"MustRunAs" #"MayRunAs", "RunAsAny"
    ranges:
      - min: 1
        max: 1000
