apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata: # kpt-merge: gatekeeper-system/config
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "policy"
        version: "v1"
        kind: "PodDisruptionBudget"
