apiVersion: v1
kind: Pod
metadata:
  name: example_disallowed_asm_ingressgateway_label_wrong_image
  labels:
    app: sleep
    asm: ingressgateway
spec:
  containers:
  - name: sleep
    image: curlimages/curl
