apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-disallowed
  name: repo-must-be-openpolicyagent-disallowed-all
spec:
  initContainers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  ephemeralContainers:
  - name: nginx2
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
