apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-disallowed
  name: example-disallowed-container
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
