apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-forbidden-sysctls-disallowed
  name: psp-forbidden-sysctls-example-allowed
  labels:
    app: nginx-forbidden-sysctls
spec:
  containers:
    - name: nginx
      image: nginx
  securityContext:
    sysctls:
      - name: net.core.somaxconn
        value: "1024"
