apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-apparmor-disallowed
  name: psp-apparmor-disallowed-ephemeral
  annotations:
    # apparmor.security.beta.kubernetes.io/pod: unconfined # runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  ephemeralContainers:
  - name: nginx2
    image: nginx
