apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-apparmor-disallowed
  name: psp-apparmor-example-disallowed
  annotations:
    # apparmor.security.beta.kubernetes.io/pod: unconfined # runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor
spec:
  containers:
  - name: nginx
    image: nginx
