apiVersion: v1
kind: Pod
metadata:
  name: no-secrets-as-env-vars-example-allowed
spec:
  containers:
  - name: test
    image: redis
    volumeMounts:
    - name: test
      mountPath: "/etc/test"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret
