apiVersion: v1
kind: Pod
metadata:
  name: no-secrets-as-env-vars-example-disallowed
spec:
  containers:
  - name: test
    image: redis
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
