apiVersion: v1
kind: Pod
metadata: # kpt-merge: /nginx-privileged-disallowed
  name: nginx-privileged-disallowed
  labels:
    app: nginx-privileged
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
