kind: Suite
apiVersion: test.gatekeeper.sh/v1alpha1
metadata:
  name: k8smemoryrequestequalslimit
tests:
  - name: k8smemoryrequestequalslimit
    template: template.yaml
    constraint: samples/container-must-request-limit/constraint.yaml
    cases:
      - name: example-allowed
        object: samples/container-must-request-limit/example_allowed.yaml
        assertions:
          - violations: no
      - name: example-disallowed
        object: samples/container-must-request-limit/example_disallowed.yaml
        assertions:
          - violations: yes
