apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /allowed-deployment
  name: replicalimits-example-allowed
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
