apiVersion: v1
kind: Pod
metadata: # kpt-merge: /opa-allowed
  name: container-must-have-cpu-requests-memory-limits-and-requests-limits-and-requests-defined-allowed
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "100m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "1Gi"
