apiVersion: v1
kind: Pod
metadata:
  name: block-process-namespace-sharing-example-disallowed
  namespace: default
spec:
  shareProcessNamespace: true
  containers:
    - name: nginx
      image: nginx
