apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: example-disallowed-predefined-header
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: "example.com"
    outputPayloadToHeader: "X-Bad-Header"