apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata: # kpt-merge: gatekeeper-system/config
  name: uniqueingresshost-sync
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
      - group: "networking.k8s.io"
        version: "v1beta1"
        kind: "Ingress"
