apiVersion: v1
kind: Service
metadata: # kpt-merge: default/gatekeeper-test-service-disallowed
  name: unique-service-selector-example-allowed
  namespace: default
spec:
  ports:
    - port: 443
  selector:
    key: other-value
